# This file was generated by GoReleaser. DO NOT EDIT.
cask "cool-notes" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "f06ce0170e5077b220d489230fe9f5d541f617f15d9e807b404b1a19db0b1c5f"
      url "https://github.com/thinkbig1979/cool-notes/releases/download/v#{version}/cool-notes_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4fa31e5b485a00b312675290c20da36678eaee021556e1b2f8dc49d6653ef46f"
      url "https://github.com/thinkbig1979/cool-notes/releases/download/v#{version}/cool-notes_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e16d7224898430abc08bc053fac8a331c7b97c7f28f5bf3ee39d8befd90b8e2b"
      url "https://github.com/thinkbig1979/cool-notes/releases/download/v#{version}/cool-notes_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "323c05f66c3299338044cd44b171a760a7d03485c61b67cae23056350ae2255c"
      url "https://github.com/thinkbig1979/cool-notes/releases/download/v#{version}/cool-notes_linux_amd64.tar.gz"
    end
  end

  name "cool-notes"
  desc "Tabbed note editor for the terminal that keeps every note in one plain-text file"
  homepage "https://github.com/thinkbig1979/cool-notes"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cool-notes"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cool-notes"]
    end
  end

  # No zap stanza required
end
