# This file was generated by GoReleaser. DO NOT EDIT.
cask "cool-notes" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "78ac77d67058c9d5b821954e91f2d3599ba40cc5c31919f9364cfbfa709822cd"
      url "https://github.com/thinkbig1979/cool-notes/releases/download/v#{version}/cool-notes_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e1b87e62cce119cd35c900a1c5fd943f8753c68f6a5314aa4578eaa9ba1af3bc"
      url "https://github.com/thinkbig1979/cool-notes/releases/download/v#{version}/cool-notes_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b48c2f505936a65e53b9441bb2e55c2b086266903acf8f884b0d08e2c498b046"
      url "https://github.com/thinkbig1979/cool-notes/releases/download/v#{version}/cool-notes_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d1a6b1243f1b8a5eb825de9483e2942255609632f259a892bf1bf57b0b213f5f"
      url "https://github.com/thinkbig1979/cool-notes/releases/download/v#{version}/cool-notes_linux_amd64.tar.gz"
    end
  end

  name "cool-notes"
  desc "Tabbed note editor for the terminal that keeps every note in one plain-text file"
  homepage "https://github.com/thinkbig1979/cool-notes"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cool-notes"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cool-notes"]
    end
  end

  # No zap stanza required
end
